repos:
  - repo: local
    hooks:
      - id: nox-quality
        name: nox -t quality
        entry: uv run nox -t quality
        language: system
        pass_filenames: false
        always_run: true
