name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test Suite
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
          python-version: "3.14"
      - name: Install dependencies
        run: uv sync --frozen --group test --extra worker
      - name: Run Unit and Integration Tests
        run: uv run pytest
